### ISSUE TITLE
getter for animal

### ISSUE THREAD

**Issue by flowolf** [smaxtec/sxapi#13]
implement a getter to get an animal (identified by animal ID)

https://api.smaxtec.com/api/v2/ -> animals should be the call to make.

goal is to have an animal object in sxapi, which can be exported as JSON.

**Comment by Mrywa** [comment]
Hey, I would like to start with this task 
Thanks :)

**Comment by Mopsgeschwindigkeit** [comment]
@Mrywa do you still want to work on this issue ?

**Comment by Mrywa** [comment]
@Mopsgeschwindigkeit you can assign it to yourself

**Comment by Mopsgeschwindigkeit** [comment]
Closing this issue since we will redefine our cli command structure!
