### ISSUE TITLE
Implement PublicApiV2 calls for animals

### ISSUE THREAD

**Issue by Mopsgeschwindigkeit** [smaxtec/sxapi#30]
Implement all supported PublicApiV2 calls regarding animals inside the `PublicAPIV2` class.

you can find a list of all supported calls here -> https://api.smaxtec.com/api/v2/ under animals.

**Comment by bloomwill** [comment]
Hello, I wanted to try my hand at contributing to this (my first GitHub contribution ever).  Should this implementation handle input validation?  For example, should the data (dict) sent to a POST method be checked against a JSON schema that matches the specifications of the smaxtec API?

For instance: POST https://api.smaxtec.com/api/v2/animals only requires organisation_id, and has multiple optional properties.  Should properties that do not exist on the API side be checked, or should it just accept the input and the client will be responsible for resolving the 422 status response?

**Comment by Mopsgeschwindigkeit** [comment]
Hello :)

To be honest, atm we are not sure which approach we want. But I will talk to @flowolf on Monday and I will update you our decision.

But i am pretty convinced that we are going for the "send all parameters you receive and let the endpoint decide wich to use and which to reject" approach.

As an implementation reference you can have a look at this this pr #35.

**Comment by flowolf** [comment]
I'd go with something pragmatic.

as schemas might change, and may even take subsets on an UPDATE call for example. 

I'd handle the server response and the error (relay the error in a message to the user). Client should stop after 422.

validating on client side may be useful (object level and within the object), but it's double the work if changes occur server side. If schemas can be synced somehow - this might vary in complexity and effort.

Does that make sense? any other suggestions?

**Comment by bloomwill** [comment]
That does make sense.  I think client-side validation would only be feasible if the API published JSON schema for each method.  Then the client could pull the schema at runtime and use that to generate objects or use a JSON validator on the kwargs

**Comment by Mopsgeschwindigkeit** [comment]
@bloomwill do you still want implement the animals endpoint ? There should be quite some implementation examples now!
