### ISSUE TITLE
publish docs to github pages

### ISSUE THREAD

**Issue by flowolf** [smaxtec/sxapi#6]
add a github workflow and publish the spinx docs, that are generated by `tox -e docs` to smaxtec.github.io/sxapi.

**Comment by Mopsgeschwindigkeit** [comment]
I would like to work on this task, if its still available :)

**Comment by flowolf** [comment]
@Mopsgeschwindigkeit assigned you.

**Comment by Mopsgeschwindigkeit** [comment]
i think we could close the issue :)

**Comment by flowolf** [comment]
thanks @Mopsgeschwindigkeit 😎
